### ISSUE TITLE
CPH2415_14.0.0.713(EX01) Magisk patched image does not seem to work

### ISSUE THREAD

**Issue by francisjeanneau** [seanwlk/oneplus10t#2]
Hi @seanwlk, I've been using your boot images since I saw your thread on XDA concerning rooting. It has always worked so far (thanks a ton by the way!), except for the 713 OS14 update. After updating & flashing the 713 patched boot image through fastboot, Magisk does not seem to be installed. I tried manually installing the v27 Magisk Manager app from Github but it reports that Magisk is not installed.

I am wondering if something changed since last version.

**Comment by seanwlk** [comment]
Hi, I think I patched it with magisk v28 since it was listed as latest version. I just checked though and from the app it shows the v27 as latest so I'm confused. 
Hadn't been using magisk for a while since I was forced to use kitsune but will patch it tomorrow and update the release file with v27

**Comment by seanwlk** [comment]
@francisjeanneau Hi, sorry for the delay had a very busy day at work. I uploaded the image again in the release and patched it with v27.

**Comment by francisjeanneau** [comment]
@seanwlk Thank you. Sadly Magisk is still not detected. Something else must be in play. I won't take more of your time, thanks again!

**Comment by francisjeanneau** [comment]
I take back what I said. I tried flashing the 712 boot image to see if it would work. Unsurprisingly, my device wouldn't boot. I then reflashed the 713 boot image and finally Magisk was detected. 

I don't know what caused this, but I'm glad it's solved now and it confirms that your patched image is good.
